name: AppOrganizer
options:
  bundleIdPrefix: com.rahul
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: "BAMVK6LBVP"
    CODE_SIGN_STYLE: Automatic

targets:
  AppOrganizer:
    type: application
    platform: iOS
    sources:
      - path: AppOrganizer
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: AppOrganizer/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.rahul.AppOrganizer
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
    info:
      path: AppOrganizer/Info.plist
      properties:
        CFBundleName: App Organizer
        CFBundleDisplayName: App Organizer
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        ITSAppUsesNonExemptEncryption: false
